### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by EpikPhailure** [EternityX/zInjector#1]
nice release, interested to see how this goes in the future
although the coding convention can be improved, if you want I can make a pull request

**Comment by EternityX** [comment]
I've always written C++ like this; I guess that's the byproduct of learning the language without proper teaching.
However, I'd love to know what you would subjectively(or objectively) improve.

**Comment by EpikPhailure** [comment]
I wouldn't say that the way you do it is necessarily wrong, however it can be changed to complement public standardization. Even the minor stuff will enhance readability.

Apologies if I sound a little demanding or whatever but it does help people to be able to maintain the same styling when working in collaborative/open-source projects. :)

Here is a guide you can look at: https://google.github.io/styleguide/cppguide.html

But I'm also a hypocrite and some of my projects still need to get out of the Valve style hungarian convention.

**Comment by EternityX** [comment]
To be honest, this is more of a personal project then anything.
If I were to actually push something that I knew was going to be publicly modified and such, I would purposely write code in a more 'standardized' way.

There's a great extension for Visual Studio I use daily called [ReSharper](https://www.jetbrains.com/resharper/) that would help with better C++ standardization.

There's some things I'll never be able to comfortably change like my preference of K&R/Stroustrup indentation, but I guess its not that bad.

**Comment by EpikPhailure** [comment]
Yeah, no problem.
Just my suggestion that holds no value. Was thinking of helping out since you made this open-source.

**Comment by EternityX** [comment]
Your suggestion definitely holds value, I just forgot the fact people write code differently lol
I'd be grateful if you decided to help, it only helps me learn more!

Obviously this project is very very basic and is sort of a base for something better

**Comment by EpikPhailure** [comment]
I luv u <3

If you could tell what you hope for zInjector to accomplish in it's final production I'll see what I can do.

**Comment by EternityX** [comment]
Similar to projects like Blackbone, I'd like to use this opportunity to learn driver development and some more advanced knowledge of Windows' inner-workings

Idealy, just a multitude of injection techniques done nicely in a small package
